image: gcc:9.3.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - wget https://cmake.org/files/v3.16/cmake-3.16.4-Linux-x86_64.tar.gz
    - tar xf cmake-3.16.4-Linux-x86_64.tar.gz
    - export PATH="`pwd`/cmake-3.16.4-Linux-x86_64/bin:$PATH"
    - cmake -S . -B build
    - cmake --build build
  only:
    - branches
  artifacts:
    name: "pso_build.${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_success
    paths:
      - build

test:NoArgs:
  stage: test
  needs:
    - build
  only:
    - branches
  script:
    - ./build/main

test:AllArgs:
  stage: test
  needs:
    - build
  only:
    - branches
  script:
    - ./build/main -v -s 100 -mig 200 -d 500 -max 50
